context:
  name: pydiverse-common
  version: "0.3.14"
  python_min: '3.10'
package:
  name: pydiverse-common
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/pydiverse-common/pydiverse_common-${{ version }}.tar.gz
    sha256: e225fab09f58bad1337fde47e5a5875211f722e0c54f21aa24612adadbd73053

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - python-box >=7.3.2,<8

tests:
  - python:
      imports:
        - pydiverse.common
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Common functionality shared between pydiverse libraries
  description: |
    A base package for different libraries in the pydiverse library collection.
    This includes functionality like a type-system for tabular data (SQL and DataFrame).
    This type-system is used for ensuring reliable operation of the pydiverse library
    with various execution backends like Pandas, Polars, and various SQL dialects.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pydiverse/pydiverse.common
  repository: https://github.com/pydiverse/pydiverse.common
  documentation: https://pydiversecommon.readthedocs.io

extra:
  recipe-maintainers:
    - pavelzw
    - windiana42
