context:
  version: "0.3.0"

package:
  name: pydiverse-common
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/p/pydiverse-common/pydiverse_common-${{ version }}.tar.gz
    sha256: 0cb6e438fe57f72995e6b12da4120626bbaa490185df03fda9a4c88039866ee7

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pydiverse.common
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Common functionality shared between pydiverse libraries
  description: |
    A base package for different libraries in the pydiverse library collection.
    This includes functionality like a type-system for tabular data (SQL and DataFrame).
    This type-system is used for ensuring reliable operation of the pydiverse library
    with various execution backends like Pandas, Polars, and various SQL dialects.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pydiverse/pydiverse.common
  repository: https://github.com/pydiverse/pydiverse.common
  documentation: https://pydiversecommon.readthedocs.io

extra:
  recipe-maintainers:
    - pavelzw
    - windiana42
